import { z } from "zod";

const envSchema = z.object({
  DATABASE_URL: z.string().min(1).optional(),
  NEXT_PUBLIC_SITE_URL: z.string().url().optional(),
  NEXT_PUBLIC_SUPABASE_URL: z.string().url().optional(),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
  ADMIN_OWNER_EMAILS: z.string().optional(),
  ADMIN_EDITOR_EMAILS: z.string().optional(),
  AFFILIATE_ALLOWED_HOSTS: z.string().optional(),
  CRON_SECRET: z.string().optional(),
  CRON_ALLOWED_IPS: z.string().optional(),
  LOG_ALERT_DENIED_24H_THRESHOLD: z.string().optional(),
  LOG_ALERT_RATE_LIMITED_24H_THRESHOLD: z.string().optional(),
  LOG_ALERT_BLOCKED_URL_24H_THRESHOLD: z.string().optional(),
  LOG_ALERT_WEBHOOK_FAILURE_RATE_24H_THRESHOLD: z.string().optional(),
  LOG_ALERT_WEBHOOK_FAILURE_RATE_MIN_ATTEMPTS_24H: z.string().optional(),
  LOG_ALERT_WEBHOOK_P95_24H_THRESHOLD_MS: z.string().optional(),
  LOG_ALERT_WEBHOOK_P95_MIN_ATTEMPTS_24H: z.string().optional(),
  LOG_ALERT_WEBHOOK_P99_24H_THRESHOLD_MS: z.string().optional(),
  LOG_ALERT_WEBHOOK_P99_MIN_ATTEMPTS_24H: z.string().optional(),
  SECURITY_ALERT_WEBHOOK_URL: z.string().optional(),
  SECURITY_ALERT_WEBHOOK_URL_WARN: z.string().optional(),
  SECURITY_ALERT_WEBHOOK_URL_CRITICAL: z.string().optional(),
  SECURITY_ALERT_CRITICAL_CONSECUTIVE_MIN: z.string().optional(),
  SECURITY_ALERT_WEBHOOK_TOKEN: z.string().optional(),
  SECURITY_ALERT_WEBHOOK_SIGNING_SECRET: z.string().optional(),
  SECURITY_ALERT_COOLDOWN_MS: z.string().optional(),
  SECURITY_ALERT_COOLDOWN_MS_WARN: z.string().optional(),
  SECURITY_ALERT_COOLDOWN_MS_CRITICAL: z.string().optional(),
  SECURITY_ALERT_SUSTAINED_WINDOW_DAYS: z.string().optional(),
  SECURITY_ALERT_SUSTAINED_MIN_BREACH_DAYS: z.string().optional(),
  SECURITY_ALERT_SKIP_LOG_WINDOW_MS: z.string().optional(),
  SECURITY_ALERT_WEBHOOK_MAX_ATTEMPTS: z.string().optional(),
  SECURITY_ALERT_WEBHOOK_BACKOFF_MS: z.string().optional(),
  SECURITY_ALERT_WEBHOOK_TIMEOUT_MS: z.string().optional(),
  SECURITY_ALERT_CRON_RATE_LIMIT_MAX: z.string().optional(),
  SECURITY_ALERT_CRON_RATE_LIMIT_WINDOW_MS: z.string().optional(),
});

export const env = envSchema.parse({
  DATABASE_URL: process.env.DATABASE_URL,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  ADMIN_OWNER_EMAILS: process.env.ADMIN_OWNER_EMAILS,
  ADMIN_EDITOR_EMAILS: process.env.ADMIN_EDITOR_EMAILS,
  AFFILIATE_ALLOWED_HOSTS: process.env.AFFILIATE_ALLOWED_HOSTS,
  CRON_SECRET: process.env.CRON_SECRET,
  CRON_ALLOWED_IPS: process.env.CRON_ALLOWED_IPS,
  LOG_ALERT_DENIED_24H_THRESHOLD: process.env.LOG_ALERT_DENIED_24H_THRESHOLD,
  LOG_ALERT_RATE_LIMITED_24H_THRESHOLD:
    process.env.LOG_ALERT_RATE_LIMITED_24H_THRESHOLD,
  LOG_ALERT_BLOCKED_URL_24H_THRESHOLD:
    process.env.LOG_ALERT_BLOCKED_URL_24H_THRESHOLD,
  LOG_ALERT_WEBHOOK_FAILURE_RATE_24H_THRESHOLD:
    process.env.LOG_ALERT_WEBHOOK_FAILURE_RATE_24H_THRESHOLD,
  LOG_ALERT_WEBHOOK_FAILURE_RATE_MIN_ATTEMPTS_24H:
    process.env.LOG_ALERT_WEBHOOK_FAILURE_RATE_MIN_ATTEMPTS_24H,
  LOG_ALERT_WEBHOOK_P95_24H_THRESHOLD_MS:
    process.env.LOG_ALERT_WEBHOOK_P95_24H_THRESHOLD_MS,
  LOG_ALERT_WEBHOOK_P95_MIN_ATTEMPTS_24H:
    process.env.LOG_ALERT_WEBHOOK_P95_MIN_ATTEMPTS_24H,
  LOG_ALERT_WEBHOOK_P99_24H_THRESHOLD_MS:
    process.env.LOG_ALERT_WEBHOOK_P99_24H_THRESHOLD_MS,
  LOG_ALERT_WEBHOOK_P99_MIN_ATTEMPTS_24H:
    process.env.LOG_ALERT_WEBHOOK_P99_MIN_ATTEMPTS_24H,
  SECURITY_ALERT_WEBHOOK_URL: process.env.SECURITY_ALERT_WEBHOOK_URL,
  SECURITY_ALERT_WEBHOOK_URL_WARN: process.env.SECURITY_ALERT_WEBHOOK_URL_WARN,
  SECURITY_ALERT_WEBHOOK_URL_CRITICAL:
    process.env.SECURITY_ALERT_WEBHOOK_URL_CRITICAL,
  SECURITY_ALERT_CRITICAL_CONSECUTIVE_MIN:
    process.env.SECURITY_ALERT_CRITICAL_CONSECUTIVE_MIN,
  SECURITY_ALERT_WEBHOOK_TOKEN: process.env.SECURITY_ALERT_WEBHOOK_TOKEN,
  SECURITY_ALERT_WEBHOOK_SIGNING_SECRET:
    process.env.SECURITY_ALERT_WEBHOOK_SIGNING_SECRET,
  SECURITY_ALERT_COOLDOWN_MS: process.env.SECURITY_ALERT_COOLDOWN_MS,
  SECURITY_ALERT_COOLDOWN_MS_WARN: process.env.SECURITY_ALERT_COOLDOWN_MS_WARN,
  SECURITY_ALERT_COOLDOWN_MS_CRITICAL:
    process.env.SECURITY_ALERT_COOLDOWN_MS_CRITICAL,
  SECURITY_ALERT_SUSTAINED_WINDOW_DAYS:
    process.env.SECURITY_ALERT_SUSTAINED_WINDOW_DAYS,
  SECURITY_ALERT_SUSTAINED_MIN_BREACH_DAYS:
    process.env.SECURITY_ALERT_SUSTAINED_MIN_BREACH_DAYS,
  SECURITY_ALERT_SKIP_LOG_WINDOW_MS: process.env.SECURITY_ALERT_SKIP_LOG_WINDOW_MS,
  SECURITY_ALERT_WEBHOOK_MAX_ATTEMPTS:
    process.env.SECURITY_ALERT_WEBHOOK_MAX_ATTEMPTS,
  SECURITY_ALERT_WEBHOOK_BACKOFF_MS: process.env.SECURITY_ALERT_WEBHOOK_BACKOFF_MS,
  SECURITY_ALERT_WEBHOOK_TIMEOUT_MS: process.env.SECURITY_ALERT_WEBHOOK_TIMEOUT_MS,
  SECURITY_ALERT_CRON_RATE_LIMIT_MAX: process.env.SECURITY_ALERT_CRON_RATE_LIMIT_MAX,
  SECURITY_ALERT_CRON_RATE_LIMIT_WINDOW_MS:
    process.env.SECURITY_ALERT_CRON_RATE_LIMIT_WINDOW_MS,
});
